CREATE TABLE IF NOT EXISTS BRAND (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS PRICE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID BIGINT,
    PRIORITY INT,
    PRICE DECIMAL(10, 2),
    CURR VARCHAR(3),
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
);

CREATE TABLE Currency (
    id INT PRIMARY KEY AUTO_INCREMENT,
    currency_code VARCHAR(3) UNIQUE
);
